trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install SDK'
  inputs:
    version: 3.1.100	
- task: Bash@3 
  displayName: 'Run Tests'
  inputs: 	 
    targetType: inline
    script: (cd sample/SampleApp; dotnet run) & (cd test/BrowserInterop.E2ETests; npm install wait-on; npm run-script wait-local; docker run -v $PWD:/e2e -w /e2e cypress/included:3.8.3 --config baseUrl=http://host.docker.internal:5000 && exit 0)
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.2'     
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: src/BrowserInterop/BrowserInterop.csproj
    versioningScheme: 'off'
    configuration: Release
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'Nuget'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), contains(variables['Build.SourceVersionMessage'], '#nuget'))
