trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install SDK'
  inputs:
    version: 3.1.100	
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.2' 
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: src/BrowserInterop/BrowserInterop.csproj
    versioningScheme: 'off'
    configuration: Release
- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: push
    nuGetFeedType: external
    externalEndPoint: 'Nuget'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), contains(variables['Build.SourceVersionMessage'], '#nuget'))
